config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  resources :books
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: {in: 2..20 }, uniqueness: true
  validates :introduction, length: {maximum: 50 }
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
  user_path(current_user.id)
  end
  def after_sign_out_path_for(resource)
  root_path
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :ensure_current_user, {only: [:edit, :update, :destroy]}

     def index
     @user = current_user
     @books = Book.all
     @book = Book.new
     end

     def show
     @user = current_user
     @book_new = Book.new
     @book = Book.find(params[:id])
     end

    def create
     @user = current_user
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
     else
      @books = Book.all
      @user = current_user
      render "index"
     end
    end

    def edit
       @book = Book.find(params[:id])
    end


   def update
       @book = Book.find(params[:id])
       if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to  book_path(@book.id)
       else
       @books = Book.all
       render "edit"
       end
   end

   def destroy
       @book = Book.find(params[:id])
       @book.destroy
       redirect_to books_path
   end

     private
     def book_params
      params.require(:book).permit(:title, :body)
     end

     def ensure_current_user
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
       redirect_to books_path
      end
     end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book =Book.new
  end

  def create
    if @users.save
    flash[:notice] = "successfully"
      redirect_to users_path
    else
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(@current_user.id)
    else
      render :edit
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= render 'layouts/error', book: @book %>
<div class="container">
    <div class="row">
        <div class="col-md-8 px5 mx-auto px-sm-0">
            <div class= "form-group">
                <h1>Editing Book</h1>
                <%= render 'layouts/error', book: @book %>
                <%= form_for(@book) do |f| %>
                <label>Title</label>
                <%= f.text_field :title, class:"form-control" %>
                <label>Opinion</label>
                <%= f.text_area :body, class:"form-control" %>
                <%= f.submit'Update Book',class:"btn btn-success mt-2" %>
                <% end %>
            </div>
            <%= link_to"Show",book_path(@book.id) %>
            <%= link_to"| Back",books_path %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/error', book: @book %>
	<div class="container">
    <div class="row">
    	<div class="col-md-3">
			<%= render 'layouts/user_info', book: @book, user: @user %>
			</div>
			<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
		    	<table class="table table-hover table-inverse">
		      		<thead>
		        		<tr>
		          			<th></th>
		          			<th>title</th>
		          			<th>opinion</th>
		          			<th colspan="3"></th>
		        		</tr>
		    		</thead>
		    		<tbody>
					  	<% @books.reverse_each do |book| %>
						<tr>
				      		<td><%= link_to user_path(book.user_id) do %>
				      			<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %></td>
				      			<% end %>
				        	<td><%= link_to book.title, book, class: "" %></td>
				        	<td><%= book.body %></td>
				     	</tr>
		        	  	<% end %>
		    		</tbody>
		      	</table>
			</div>
		</div>
	</div>

<div class="container mt-5">
	<div class="row">
		<div class="mx-auto">
		      <p>CopyRight Infratop.inc</p>
		</div>
  </div>
</div>

app/views/books/show.html.erb
<div class="box">
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>

<div class="container">
    <div class="row">
    	<div class="col-md-3">
		<h2>User info</h2>
    <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class = "table">
            <tbody>
              <tr>
                <th>name</th>
                <td><%= @book.user.name %></td>
              </tr>
              <tr>
                <th>introduction</th>
                <td><%= @book.user.introduction %></td>
              </tr>
            </tbody>
        </table>
        <%= link_to "", edit_user_path(@book.user.id),  class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
<h2>New book</h2>
      <%= form_for(@book_new, url:books_path) do |f| %>
      <div class= "form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class= "form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class= "form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
      <% end %>


		</div>
		<div class="col-md-8 offset-md-1">
		<h2>Book detail</h2>
                <table class="table">
                    <tr>
                    <td>
                    <%= link_to user_path(@book.user_id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'50x50',format: 'no_image.jpg' %>
                    <nav>
                        <%= @book.user.name %>
                    </nav>
                    <% end %>
                    </td>
                    <td><%= link_to @book.title %></td>
                    <td><%= @book.body %></td>

                    <% if @book.user_id == current_user.id %>
                    <td><%= link_to"Edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
                    <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger destroy(@book.id)", method: :delete,data: {confirm: "削除しますか？"} %></td>
                    <% end %>
                    </tr>
		      	</table>
		</div>
	</div>
</div>

<div class="container mt-5">
	<div class="row">
		<div class="mx-auto">
		      <p>CopyRight Infratop.inc</p>
		</div>
  	</div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
<div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
</div>

app/views/homes/top.html.erb
<h1>welcome to
 <i class="fas fa-book"></i>
 <strong>Bookers</strong>
 !!
</h1>
<p>In
<i class="fas fa-book"></i>
<strong>Bookers</strong>
,
</p>
<p>you can share and exchange  your opinions , inpressions , and emotions</p>

<p> about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
   <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
  </div>
  <div class="row">
   <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
  </div>
</div>




<div class="mx-auto">
 <p>CopyRight Infratop.inc</p>
</div>

app/views/layouts/_error.html.erb
<%#=<%= render 'layouts/error', book: @book %>


<% if book.errors.any? %>
<div id="error_messages">
    <h3><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
    <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_user_info.html.erb
 <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class = "table">
            <tbody>
              <tr>
                <th>name</th>
                <td><%= user.name %></td>
              </tr>
              <tr>
                <th>introduction</th>
                <td><%= user.introduction %></td>
              </tr>
            </tbody>
        </table>
        <%= link_to "", edit_user_path(user),  class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
<h2>New book</h2>
      <%= form_for(book) do |f| %>
      <div class= "form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class= "form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class= "form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <h4><a class="navbar-brand p-3" href="/">Bookers</a></h4>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to ' Home', user_path(current_user.id), class: ' text-dark fas fa-home nav-link ' %>
            </li>
             <li class="nav-item">
              <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-dark' %>
            </li>
            <li>
              <%= link_to ' Books', books_path, class:' fas fa-book-open nav-link text-dark ' %>
            </li>
            <li>
             <%= link_to ' logout', destroy_user_session_path, method: :delete, class:'fas fa-sign-out-alt nav-link text-dark' %>
            </li>
            <% else %>
            <li>
              <a class="fas fa-home nav-link text-light" href="/"> Home</a>
            </li>
            <li>
              <a class="fas fa-link nav-link text-light" href="/home/about"> About</a>
            </li>
            <li>
            <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> Sign up</a>
            </li>
            <li>
              <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% flash.each do |key, value| %>
      <p class="notice notice-<% key %>">
      <%= value %>
      </p>
      <% end %>
   <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_messages">
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h3>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>


<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
<div class="form-group">
  <label for="Name">Name</label>
  <%= f.text_field :name, autofocus: true, id:"Name", placeholder:"名前", class:"form-control"%>
</div>
<div class="form-group">
<div><label for="Image">Image</label></div>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
</div>
<div class="form-group">
  <label for="user_introduction">Introduction</label>
  <%= f.text_area :introduction, class:"form-control introduction" %>
</div>
  <%= f.submit "Update User" %>
<% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
    	<div class="col-md-3">
			<%= render 'layouts/user_info', book: @book, user: @user %>
		</div>
		<div class="col-md-8 offset-md-1">
		<h2>Users</h2>
		    	<table class="table-hover table-inverse">
		      		<thead>
		        		<tr>
		          			<th></th>
		          			<th>image</th>
		          			<th>name</th>
		          			<th colspan="3"></th>
		        		</tr>
                    </thead>

                    <tbody>
					  	<% @users.reverse_each do |user| %>
                             <tr>
                             <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
                             <td><%= user.name %></td>
                             <td><%= link_to "Show", user_path(user.id) %></td>
                             </tr>
                             <% end %>
                             </table>
				     	</tr>
		    		</tbody>
		      	</table>
		</div>
		</div>
		</div>

		<div class="container mt-5">
		<div class="row">
		<div class="mx-auto">
		      <p>CopyRight Infratop.inc</p>
		</div>
  	</div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
    	<div class="col-md-3">
			<%= render 'layouts/user_info', book: @book, user: @user %>
		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			    	<table class="table">
			      		<thead>
			        		<tr>
			          			<th></th>
			          			<th>title</th>
			          			<th>opinion</th>
			          			<th colspan="3"></th>
			        		</tr>
	                    </thead>

	                    <tbody>
						  	<% @books.reverse_each do |book| %>
	                             <tr>
	                             <%= link_to user_path(@user.id) do %>
	                             <td><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
	                             <% end %>
	                             <td><%=link_to book.title, book_path(book.id)%></td>
	                             <td><%= book.body %></td>
	                             </tr>
	                             <% end %>
	                             </table>
					     	</tr>
			    		</tbody>
			      	</table>
		</div>
	</div>
</div>

		<div class="container mt-5">
		<div class="row">
		<div class="mx-auto">
		      <p>CopyRight Infratop.inc</p>
		</div>
  	</div>
</div>